from email.message import EmailMessage
from Crypto.Cipher import AES
from hashlib import md5
from binascii import hexlify
from binascii import unhexlify
import smtplib
import imghdr
import time
import psutil

print('Welcome to Tamil Cipher')

from googletrans import Translator
def tamildetrans(string):
    translator = Translator()
    translate_text = translator.translate(string, src='ta', dest='en')  
    return translate_text

def tamilremap(string):   
    string = string.replace("AA",u"அ")
    string = string.replace("AB",u"ஆ")
    string = string.replace("AC",u"இ")
    string = string.replace("AD",u"ஈ")
    string = string.replace("AE",u"உ")
    string = string.replace("AF",u"ஊ")
    string = string.replace("AG",u"எ")
    string = string.replace("AH",u"ஏ")
    string = string.replace("AI",u"ஐ")
    string = string.replace("AJ",u"ஒ")
    string = string.replace("AK",u"ஓ")
    string = string.replace("AL",u"ஔ")
    string = string.replace("AM",u"ஃ")
    
    string = string.replace("AN",u"க")
    string = string.replace("AO",u"ங")
    string = string.replace("AP",u"ச")
    string = string.replace("AQ",u"ஞ")
    string = string.replace("AR",u"ட")
    string = string.replace("AS",u"ண")
    string = string.replace("AT",u"த")
    string = string.replace("AU",u"ந")
    string = string.replace("AV",u"ப")
    string = string.replace("AW",u"ம")
    string = string.replace("AX",u"ய")
    string = string.replace("AY",u"ர")
    string = string.replace("AZ",u"ல")
    string = string.replace("BA",u"வ")
    string = string.replace("BB",u"ழ")
    string = string.replace("BC",u"ள")
    string = string.replace("BD",u"ற")
    string = string.replace("BE",u"ன")
    
    string = string.replace("BF",u"கா")
    string = string.replace("BG",u"ஙா")
    string = string.replace("BH",u"சா")
    string = string.replace("BI",u"ஞா")
    string = string.replace("BJ",u"டா")
    string = string.replace("BK",u"ணா")
    string = string.replace("BL",u"தா")
    string = string.replace("BM",u"நா")
    string = string.replace("BN",u"பா")
    string = string.replace("BO",u"மா")
    string = string.replace("BP",u"யா")
    string = string.replace("BQ",u"ரா")
    string = string.replace("BR",u"லா")
    string = string.replace("BS",u"வா")
    string = string.replace("BT",u"ழா")
    string = string.replace("BU",u"ளா")
    string = string.replace("BV",u"றா")
    string = string.replace("BW",u"னா")
    
    string = string.replace("BX",u"கி")
    string = string.replace("BY",u"ஙி")
    string = string.replace("BZ",u"சி")
    string = string.replace("CA",u"ஞி")
    string = string.replace("CB",u"டி")
    string = string.replace("CC",u"ணி")
    string = string.replace("CD",u"தி")
    string = string.replace("CE",u"நி")
    string = string.replace("CF",u"பி")
    string = string.replace("CG",u"மி")
    string = string.replace("CH",u"யி")
    string = string.replace("CI",u"ரி")
    string = string.replace("CJ",u"லி")
    string = string.replace("CK",u"வி")
    string = string.replace("CL",u"ழி")
    string = string.replace("CM",u"ளி")
    string = string.replace("CN",u"றி")
    string = string.replace("CO",u"னி")
    
    string = string.replace("CP",u"கீ")
    string = string.replace("CQ",u"ஙீ")
    string = string.replace("CR",u"சீ")
    string = string.replace("CS",u"ஞீ")
    string = string.replace("CT",u"டீ")
    string = string.replace("CU",u"ணீ")
    string = string.replace("CV",u"தீ")
    string = string.replace("CW",u"நீ")
    string = string.replace("CX",u"பீ")
    string = string.replace("CY",u"மீ")
    string = string.replace("CZ",u"யீ")
    string = string.replace("DA",u"ரீ")
    string = string.replace("DB",u"லீ")
    string = string.replace("DC",u"வீ")
    string = string.replace("DD",u"ழீ")
    string = string.replace("DE",u"ளீ")
    string = string.replace("DF",u"றீ")
    string = string.replace("DG",u"னீ")
    
    string = string.replace("DH",u"கு")
    string = string.replace("DI",u"ஙு")
    string = string.replace("DJ",u"சு")
    string = string.replace("DK",u"ஞு")
    string = string.replace("DL",u"டு")
    string = string.replace("DM",u"ணு")
    string = string.replace("DN",u"து")
    string = string.replace("DO",u"நு")
    string = string.replace("DP",u"பு")
    string = string.replace("DQ",u"மு")
    string = string.replace("DR",u"யு")
    string = string.replace("DS",u"ரு")
    string = string.replace("DT",u"லு")
    string = string.replace("DU",u"வு")
    string = string.replace("DV",u"ழு")
    string = string.replace("DW",u"ளு")
    string = string.replace("DX",u"று")
    string = string.replace("DY",u"னு")
    
    string = string.replace("DZ",u"கூ")
    string = string.replace("EA",u"ஙூ")
    string = string.replace("EB",u"சூ")
    string = string.replace("EC",u"ஞூ")
    string = string.replace("ED",u"டூ")
    string = string.replace("EE",u"ணூ")
    string = string.replace("EF",u"தூ")
    string = string.replace("EG",u"நூ")
    string = string.replace("EH",u"பூ")
    string = string.replace("EI",u"மூ")
    string = string.replace("EJ",u"யூ")
    string = string.replace("EK",u"ரூ")
    string = string.replace("EL",u"லூ")
    string = string.replace("EM",u"வூ")
    string = string.replace("EN",u"ழூ")
    string = string.replace("EO",u"ளூ")
    string = string.replace("EP",u"றூ")
    string = string.replace("EQ",u"னூ")
    
    string = string.replace("ER",u"கெ")
    string = string.replace("ES",u"ஙெ")
    string = string.replace("ET",u"செ")
    string = string.replace("EU",u"ஞெ")
    string = string.replace("EV",u"டெ")
    string = string.replace("EW",u"ணெ")
    string = string.replace("EX",u"தெ")
    string = string.replace("EY",u"நெ")
    string = string.replace("EZ",u"பெ")
    string = string.replace("FA",u"மெ")
    string = string.replace("FB",u"யெ")
    string = string.replace("FC",u"ரெ")
    string = string.replace("FD",u"லெ")
    string = string.replace("FE",u"வெ")
    string = string.replace("FF",u"ழெ")
    string = string.replace("FG",u"ளெ")
    string = string.replace("FH",u"றெ")
    string = string.replace("FI",u"னெ")
    
    string = string.replace("FJ",u"கே")
    string = string.replace("FK",u"ஙே")
    string = string.replace("FL",u"சே")
    string = string.replace("FM",u"ஞே")
    string = string.replace("FN",u"டே")
    string = string.replace("FO",u"ணே")
    string = string.replace("FP",u"தே")
    string = string.replace("FQ",u"நே")
    string = string.replace("FR",u"பே")
    string = string.replace("FS",u"மே")
    string = string.replace("FT",u"யே")
    string = string.replace("FU",u"ரே")
    string = string.replace("FV",u"லே")
    string = string.replace("FW",u"வே")
    string = string.replace("FX",u"ழே")
    string = string.replace("FY",u"ளே")
    string = string.replace("FZ",u"றே")
    string = string.replace("GA",u"னே")
    
    string = string.replace("GB",u"கை")
    string = string.replace("GC",u"ஙை")
    string = string.replace("GD",u"சை")
    string = string.replace("GE",u"ஞை")
    string = string.replace("GF",u"டை")
    string = string.replace("GG",u"ணை")
    string = string.replace("GH",u"தை")
    string = string.replace("GI",u"நை")
    string = string.replace("GJ",u"பை")
    string = string.replace("GK",u"மை")
    string = string.replace("GL",u"யை")
    string = string.replace("GM",u"ரை")
    string = string.replace("GN",u"லை")
    string = string.replace("GO",u"வை")
    string = string.replace("GP",u"ழை")
    string = string.replace("GQ",u"ளை")
    string = string.replace("GR",u"றை")
    string = string.replace("GS",u"னை")
    
    string = string.replace("GT",u"கொ")
    string = string.replace("GU",u"ஙொ")
    string = string.replace("GV",u"சொ")
    string = string.replace("GW",u"ஞொ")
    string = string.replace("GX",u"டொ")
    string = string.replace("GY",u"ணொ")
    string = string.replace("GZ",u"தொ")
    string = string.replace("HA",u"நொ")
    string = string.replace("HB",u"பொ")
    string = string.replace("HC",u"மொ")
    string = string.replace("HD",u"யொ")
    string = string.replace("HE",u"ரொ")
    string = string.replace("HF",u"லொ")
    string = string.replace("HG",u"வொ")
    string = string.replace("HH",u"ழொ")
    string = string.replace("HI",u"ளொ")
    string = string.replace("HJ",u"றொ")
    string = string.replace("HK",u"னொ")
    
    string = string.replace("HL",u"கோ")
    string = string.replace("HM",u"ஙோ")
    string = string.replace("HN",u"சோ")
    string = string.replace("HO",u"ஞோ")
    string = string.replace("HP",u"டோ")
    string = string.replace("HQ",u"ணோ")
    string = string.replace("HR",u"தோ")
    string = string.replace("HS",u"நோ")
    string = string.replace("HT",u"போ")
    string = string.replace("HU",u"மோ")
    string = string.replace("HV",u"யோ")
    string = string.replace("HW",u"ரோ")
    string = string.replace("HX",u"லோ")
    string = string.replace("HY",u"வோ")
    string = string.replace("HZ",u"ழோ")
    string = string.replace("IA",u"ளோ")
    string = string.replace("IB",u"றோ")
    string = string.replace("IC",u"னோ")
    
    string = string.replace("ID",u"கௌ")
    string = string.replace("IE",u"ஙௌ")
    string = string.replace("IF",u"சௌ")
    string = string.replace("IG",u"ஞௌ")
    string = string.replace("IH",u"டௌ")
    string = string.replace("II",u"ணௌ")
    string = string.replace("IJ",u"தௌ")
    string = string.replace("IK",u"நௌ")
    string = string.replace("IL",u"பௌ")
    string = string.replace("IM",u"மௌ")
    string = string.replace("IN",u"யௌ")
    string = string.replace("IO",u"ரௌ")
    string = string.replace("IP",u"லௌ")
    string = string.replace("IQ",u"வௌ")
    string = string.replace("IR",u"ழௌ")
    string = string.replace("IS",u"ளௌ")
    string = string.replace("IT",u"றௌ")
    string = string.replace("IU",u"னௌ")
    
    string = string.replace("IV",u"க்")
    string = string.replace("IW",u"ங்")
    string = string.replace("IX",u"ச்")
    string = string.replace("IY",u"ஞ்")
    string = string.replace("IZ",u"ட்")
    string = string.replace("JA",u"ண்")
    string = string.replace("JB",u"த்")
    string = string.replace("JC",u"ந்")
    string = string.replace("JD",u"ப்")
    string = string.replace("JE",u"ம்")
    string = string.replace("JF",u"ய்")
    string = string.replace("JG",u"ர்")
    string = string.replace("JH",u"ல்")
    string = string.replace("JI",u"வ்")
    string = string.replace("JJ",u"ழ்")
    string = string.replace("JK",u"ள்")
    string = string.replace("JL",u"ற்")
    string = string.replace("JM",u"ன்")
        
    string = string.replace("JN",u"ஸ")
    string = string.replace("JO",u"ஷ")
    string = string.replace("JP",u"ஜ")
    string = string.replace("JQ",u"ஹ")
    string = string.replace("JR",u"க்ஷ")
    string = string.replace("JS",u"ஶ்ரீ")
    
    string = string.replace("JT",u"ஸா")
    string = string.replace("JU",u"ஷா")
    string = string.replace("JV",u"ஜா")
    string = string.replace("JW",u"ஹா")
    string = string.replace("JX",u"க்ஷா")
    
    string = string.replace("JY",u"ஸி")
    string = string.replace("JZ",u"ஷி")
    string = string.replace("KA",u"ஜி")
    string = string.replace("KB",u"ஹி")
    string = string.replace("KC",u"க்ஷி")
    
    string = string.replace("KD",u"ஸீ")
    string = string.replace("KE",u"க்ஷீ")
    string = string.replace("KF",u"ஜீ")
    string = string.replace("KG",u"ஹீ")
    string = string.replace("KH",u"க்ஷீ")
    
    string = string.replace("KI",u"ஸு")
    string = string.replace("KJ",u"ஷு")
    string = string.replace("KK",u"ஜு")
    string = string.replace("KL",u"ஹு")
    string = string.replace("KM",u"க்ஷு")
    
    string = string.replace("KN",u"ஸூ")
    string = string.replace("KO",u"ஷூ")
    string = string.replace("KP",u"ஜூ")
    string = string.replace("KQ",u"ஹூ")
    string = string.replace("KR",u"க்ஷூ")
    
    string = string.replace("KS",u"ஸெ")
    string = string.replace("KT",u"ஷெ")
    string = string.replace("KU",u"ஜெ")
    string = string.replace("KV",u"ஹெ")
    string = string.replace("KW",u"க்ஷெ")
    
    string = string.replace("KX",u"ஸே")
    string = string.replace("KY",u"ஷே")
    string = string.replace("KZ",u"ஜே")
    string = string.replace("LA",u"ஹே")
    string = string.replace("LB",u"க்ஷே")
    
    string = string.replace("LC",u"ஸை")
    string = string.replace("LD",u"ஷை")
    string = string.replace("LE",u"ஜை")
    string = string.replace("LF",u"ஹை")
    string = string.replace("LG",u"க்ஷை")
    
    string = string.replace("LH",u"ஸொ")
    string = string.replace("LI",u"ஷொ")
    string = string.replace("LJ",u"ஜொ")
    string = string.replace("LK",u"ஹொ")
    string = string.replace("LL",u"க்ஷொ")
    
    string = string.replace("LM",u"ஸோ")
    string = string.replace("LN",u"ஷோ")
    string = string.replace("LO",u"ஜோ")
    string = string.replace("LP",u"ஹோ")
    string = string.replace("LQ",u"க்ஷோ")
    
    string = string.replace("LR",u"ஸௌ")
    string = string.replace("LS",u"ஷௌ")
    string = string.replace("LT",u"ஜௌ")
    string = string.replace("LU",u"ஹௌ")
    string = string.replace("LV",u"க்ஷௌ")
    
    string = string.replace("LW",u"ஸ்")
    string = string.replace("LX",u"ஷ்")
    string = string.replace( "LY",u"ஜ்")
    string = string.replace("LZ",u"ஹ்")
    string = string.replace("MA",u"க்ஷ்")
    
    return string

def dec(text):
    key = input('Enter your AES key: \n')
    key_hash = md5(key.encode('ascii')).digest()
    mode = AES.MODE_EAX
    cipher = AES.new(key_hash, mode, nonce=b'0') ##AES ALGORITHM
    ciphertext = cipher.decrypt(text)
    return ciphertext

##DECRYPTION

start = time.time()

mailcontent = input('Enter the mail content to be decrypted: \n')
mailhex = unhexlify(mailcontent) #do both hex and string -> byte conversion
ciphertext = dec(mailhex)
print('Encrypted Text as string: \n',mailcontent)
print('Encrypted Text: \n', mailhex)

ptadec = ciphertext.decode("utf-8")
print('Remapped Text: \n', ptadec)

ptadec = ptadec.replace(" ", "**")
n = 2
ptadec = [(ptadec[i:i+n]) for i in range(0, len(ptadec), n)]
ptadec = ' '.join([str(elem) for elem in ptadec])

remap = tamilremap(ptadec)
remap = remap.replace(" ", "")
remap = remap.replace("**", " ")
print('Translated Text: \n', remap)

detrans = tamildetrans(remap)
print('Plain Text: \n',detrans.text)

print("--- %s seconds ---" % ((time.time() - start)*1000))
print("CPU % used:", psutil.cpu_percent())
#print(psutil.virtual_memory())  # physical memory usage
print('memory % used:', psutil.virtual_memory()[2])
print('disk % used:', psutil.disk_usage('/'))
#print('disk % used:', psutil.disk_usage()[3])
