from email.message import EmailMessage
from Crypto.Cipher import AES
from hashlib import md5
from binascii import hexlify
from binascii import unhexlify
import smtplib
import imghdr
import time
import psutil

print('Welcome to Tamil Cipher')

from googletrans import Translator
def tamiltrans(string):
    translator = Translator()
    translate_text = translator.translate(string, src='en', dest='ta') 
    return translate_text

from tamil import utf8
def tamilmap(string):
    string = string.replace(u"கா", "BF")
    string = string.replace(u"ஙா", "BG")
    string = string.replace(u"சா", "BH")
    string = string.replace(u"ஞா", "BI")
    string = string.replace(u"டா", "BJ")
    string = string.replace(u"ணா", "BK")
    string = string.replace(u"தா", "BL")
    string = string.replace(u"நா", "BM")
    string = string.replace(u"பா", "BN")
    string = string.replace(u"மா", "BO")
    string = string.replace(u"யா", "BP")
    string = string.replace(u"ரா", "BQ")
    string = string.replace(u"லா", "BR")
    string = string.replace(u"வா", "BS")
    string = string.replace(u"ழா", "BT")
    string = string.replace(u"ளா", "BU")
    string = string.replace(u"றா", "BV")
    string = string.replace(u"னா", "BW")
    
    string = string.replace(u"கி", "BX")
    string = string.replace(u"ஙி", "BY")
    string = string.replace(u"சி", "BZ")
    string = string.replace(u"ஞி", "CA")
    string = string.replace(u"டி", "CB")
    string = string.replace(u"ணி", "CC")
    string = string.replace(u"தி", "CD")
    string = string.replace(u"நி", "CE")
    string = string.replace(u"பி", "CF")
    string = string.replace(u"மி", "CG")
    string = string.replace(u"யி", "CH")
    string = string.replace(u"ரி", "CI")
    string = string.replace(u"லி", "CJ")
    string = string.replace(u"வி", "CK")
    string = string.replace(u"ழி", "CL")
    string = string.replace(u"ளி", "CM")
    string = string.replace(u"றி", "CN")
    string = string.replace(u"னி", "CO")
    
    string = string.replace(u"கீ", "CP")
    string = string.replace(u"ஙீ", "CQ")
    string = string.replace(u"சீ", "CR")
    string = string.replace(u"ஞீ", "CS")
    string = string.replace(u"டீ", "CT")
    string = string.replace(u"ணீ", "CU")
    string = string.replace(u"தீ", "CV")
    string = string.replace(u"நீ", "CW")
    string = string.replace(u"பீ", "CX")
    string = string.replace(u"மீ", "CY")
    string = string.replace(u"யீ", "CZ")
    string = string.replace(u"ரீ", "DA")
    string = string.replace(u"லீ", "DB")
    string = string.replace(u"வீ", "DC")
    string = string.replace(u"ழீ", "DD")
    string = string.replace(u"ளீ", "DE")
    string = string.replace(u"றீ", "DF")
    string = string.replace(u"னீ", "DG")
    
    string = string.replace(u"கு", "DH")
    string = string.replace(u"ஙு", "DI")
    string = string.replace(u"சு", "DJ")
    string = string.replace(u"ஞு", "DK")
    string = string.replace(u"டு", "DL")
    string = string.replace(u"ணு", "DM")
    string = string.replace(u"து", "DN")
    string = string.replace(u"நு", "DO")
    string = string.replace(u"பு", "DP")
    string = string.replace(u"மு", "DQ")
    string = string.replace(u"யு", "DR")
    string = string.replace(u"ரு", "DS")
    string = string.replace(u"லு", "DT")
    string = string.replace(u"வு", "DU")
    string = string.replace(u"ழு", "DV")
    string = string.replace(u"ளு", "DW")
    string = string.replace(u"று", "DX")
    string = string.replace(u"னு", "DY")
    
    string = string.replace(u"கூ", "DZ")
    string = string.replace(u"ஙூ", "EA")
    string = string.replace(u"சூ", "EB")
    string = string.replace(u"ஞூ", "EC")
    string = string.replace(u"டூ", "ED")
    string = string.replace(u"ணூ", "EE")
    string = string.replace(u"தூ", "EF")
    string = string.replace(u"நூ", "EG")
    string = string.replace(u"பூ", "EH")
    string = string.replace(u"மூ", "EI")
    string = string.replace(u"யூ", "EJ")
    string = string.replace(u"ரூ", "EK")
    string = string.replace(u"லூ", "EL")
    string = string.replace(u"வூ", "EM")
    string = string.replace(u"ழூ", "EN")
    string = string.replace(u"ளூ", "EO")
    string = string.replace(u"றூ", "EP")
    string = string.replace(u"னூ", "EQ")
    
    string = string.replace(u"கெ", "ER")
    string = string.replace(u"ஙெ", "ES")
    string = string.replace(u"செ", "ET")
    string = string.replace(u"ஞெ", "EU")
    string = string.replace(u"டெ", "EV")
    string = string.replace(u"ணெ", "EW")
    string = string.replace(u"தெ", "EX")
    string = string.replace(u"நெ", "EY")
    string = string.replace(u"பெ", "EZ")
    string = string.replace(u"மெ", "FA")
    string = string.replace(u"யெ", "FB")
    string = string.replace(u"ரெ", "FC")
    string = string.replace(u"லெ", "FD")
    string = string.replace(u"வெ", "FE")
    string = string.replace(u"ழெ", "FF")
    string = string.replace(u"ளெ", "FG")
    string = string.replace(u"றெ", "FH")
    string = string.replace(u"னெ", "FI")
    
    string = string.replace(u"கே", "FJ")
    string = string.replace(u"ஙே", "FK")
    string = string.replace(u"சே", "FL")
    string = string.replace(u"ஞே", "FM")
    string = string.replace(u"டே", "FN")
    string = string.replace(u"ணே", "FO")
    string = string.replace(u"தே", "FP")
    string = string.replace(u"நே", "FQ")
    string = string.replace(u"பே", "FR")
    string = string.replace(u"மே", "FS")
    string = string.replace(u"யே", "FT")
    string = string.replace(u"ரே", "FU")
    string = string.replace(u"லே", "FV")
    string = string.replace(u"வே", "FW")
    string = string.replace(u"ழே", "FX")
    string = string.replace(u"ளே", "FY")
    string = string.replace(u"றே", "FZ")
    string = string.replace(u"னே", "GA")
    
    string = string.replace(u"கை", "GB")
    string = string.replace(u"ஙை", "GC")
    string = string.replace(u"சை", "GD")
    string = string.replace(u"ஞை", "GE")
    string = string.replace(u"டை", "GF")
    string = string.replace(u"ணை", "GG")
    string = string.replace(u"தை", "GH")
    string = string.replace(u"நை", "GI")
    string = string.replace(u"பை", "GJ")
    string = string.replace(u"மை", "GK")
    string = string.replace(u"யை", "GL")
    string = string.replace(u"ரை", "GM")
    string = string.replace(u"லை", "GN")
    string = string.replace(u"வை", "GO")
    string = string.replace(u"ழை", "GP")
    string = string.replace(u"ளை", "GQ")
    string = string.replace(u"றை", "GR")
    string = string.replace(u"னை", "GS")
    
    string = string.replace(u"கொ", "GT")
    string = string.replace(u"ஙொ", "GU")
    string = string.replace(u"சொ", "GV")
    string = string.replace(u"ஞொ", "GW")
    string = string.replace(u"டொ", "GX")
    string = string.replace(u"ணொ", "GY")
    string = string.replace(u"தொ", "GZ")
    string = string.replace(u"நொ", "HA")
    string = string.replace(u"பொ", "HB")
    string = string.replace(u"மொ", "HC")
    string = string.replace(u"யொ", "HD")
    string = string.replace(u"ரொ", "HE")
    string = string.replace(u"லொ", "HF")
    string = string.replace(u"வொ", "HG")
    string = string.replace(u"ழொ", "HH")
    string = string.replace(u"ளொ", "HI")
    string = string.replace(u"றொ", "HJ")
    string = string.replace(u"னொ", "HK")
    
    string = string.replace(u"கோ", "HL")
    string = string.replace(u"ஙோ", "HM")
    string = string.replace(u"சோ", "HN")
    string = string.replace(u"ஞோ", "HO")
    string = string.replace(u"டோ", "HP")
    string = string.replace(u"ணோ", "HQ")
    string = string.replace(u"தோ", "HR")
    string = string.replace(u"நோ", "HS")
    string = string.replace(u"போ", "HT")
    string = string.replace(u"மோ", "HU")
    string = string.replace(u"யோ", "HV")
    string = string.replace(u"ரோ", "HW")
    string = string.replace(u"லோ", "HX")
    string = string.replace(u"வோ", "HY")
    string = string.replace(u"ழோ", "HZ")
    string = string.replace(u"ளோ", "IA")
    string = string.replace(u"றோ", "IB")
    string = string.replace(u"னோ", "IC")
    
    string = string.replace(u"கௌ", "ID")
    string = string.replace(u"ஙௌ", "IE")
    string = string.replace(u"சௌ", "IF")
    string = string.replace(u"ஞௌ", "IG")
    string = string.replace(u"டௌ", "IH")
    string = string.replace(u"ணௌ", "II")
    string = string.replace(u"தௌ", "IJ")
    string = string.replace(u"நௌ", "IK")
    string = string.replace(u"பௌ", "IL")
    string = string.replace(u"மௌ", "IM")
    string = string.replace(u"யௌ", "IN")
    string = string.replace(u"ரௌ", "IO")
    string = string.replace(u"லௌ", "IP")
    string = string.replace(u"வௌ", "IQ")
    string = string.replace(u"ழௌ", "IR")
    string = string.replace(u"ளௌ", "IS")
    string = string.replace(u"றௌ", "IT")
    string = string.replace(u"னௌ", "IU")
    
    string = string.replace(u"க்", "IV")
    string = string.replace(u"ங்", "IW")
    string = string.replace(u"ச்", "IX")
    string = string.replace(u"ஞ்", "IY")
    string = string.replace(u"ட்", "IZ")
    string = string.replace(u"ண்", "JA")
    string = string.replace(u"த்", "JB")
    string = string.replace(u"ந்", "JC")
    string = string.replace(u"ப்", "JD")
    string = string.replace(u"ம்", "JE")
    string = string.replace(u"ய்", "JF")
    string = string.replace(u"ர்", "JG")
    string = string.replace(u"ல்", "JH")
    string = string.replace(u"வ்", "JI")
    string = string.replace(u"ழ்", "JJ")
    string = string.replace(u"ள்", "JK")
    string = string.replace(u"ற்", "JL")
    string = string.replace(u"ன்", "JM")
    
    string = string.replace(u"அ", "AA")
    string = string.replace(u"ஆ", "AB")
    string = string.replace(u"இ", "AC")
    string = string.replace(u"ஈ", "AD")
    string = string.replace(u"உ", "AE")
    string = string.replace(u"ஊ", "AF")
    string = string.replace(u"எ", "AG")
    string = string.replace(u"ஏ", "AH")
    string = string.replace(u"ஐ", "AI")
    string = string.replace(u"ஒ", "AJ")
    string = string.replace(u"ஓ", "AK")
    string = string.replace(u"ஔ", "AL")
    string = string.replace(u"ஃ", "AM")
    
    string = string.replace(u"க", "AN")
    string = string.replace(u"ங", "AO")
    string = string.replace(u"ச", "AP")
    string = string.replace(u"ஞ", "AQ")
    string = string.replace(u"ட", "AR")
    string = string.replace(u"ண", "AS")
    string = string.replace(u"த", "AT")
    string = string.replace(u"ந", "AU")
    string = string.replace(u"ப", "AV")
    string = string.replace(u"ம", "AW")
    string = string.replace(u"ய", "AX")
    string = string.replace(u"ர", "AY")
    string = string.replace(u"ல", "AZ")
    string = string.replace(u"வ", "BA")
    string = string.replace(u"ழ", "BB")
    string = string.replace(u"ள", "BC")
    string = string.replace(u"ற", "BD")
    string = string.replace(u"ன", "BE")
    
    string = string.replace(u"ஸா", "JT")
    string = string.replace(u"ஷா", "JU")
    string = string.replace(u"ஜா", "JV")
    string = string.replace(u"ஹா", "JW")
    string = string.replace(u"க்ஷா", "JX")
    
    string = string.replace(u"ஸி", "JY")
    string = string.replace(u"ஷி", "JZ")
    string = string.replace(u"ஜி", "KA")
    string = string.replace(u"ஹி", "KB")
    string = string.replace(u"க்ஷி", "KC")
    
    string = string.replace(u"ஸீ", "KD")
    string = string.replace(u"க்ஷீ", "KE")
    string = string.replace(u"ஜீ", "KF")
    string = string.replace(u"ஹீ", "KG")
    string = string.replace(u"க்ஷீ", "KH")
    
    string = string.replace(u"ஸு", "KI")
    string = string.replace(u"ஷு", "KJ")
    string = string.replace(u"ஜு", "KK")
    string = string.replace(u"ஹு", "KL")
    string = string.replace(u"க்ஷு", "KM")
    
    string = string.replace(u"ஸூ", "KN")
    string = string.replace(u"ஷூ", "KO")
    string = string.replace(u"ஜூ", "KP")
    string = string.replace(u"ஹூ", "KQ")
    string = string.replace(u"க்ஷூ", "KR")
    
    string = string.replace(u"ஸெ", "KS")
    string = string.replace(u"ஷெ", "KT")
    string = string.replace(u"ஜெ", "KU")
    string = string.replace(u"ஹெ", "KV")
    string = string.replace(u"க்ஷெ", "KW")
    
    string = string.replace(u"ஸே", "KX")
    string = string.replace(u"ஷே", "KY")
    string = string.replace(u"ஜே", "KZ")
    string = string.replace(u"ஹே", "LA")
    string = string.replace(u"க்ஷே", "LB")
    
    string = string.replace(u"ஸை", "LC")
    string = string.replace(u"ஷை", "LD")
    string = string.replace(u"ஜை", "LE")
    string = string.replace(u"ஹை", "LF")
    string = string.replace(u"க்ஷை", "LG")
    
    string = string.replace(u"ஸொ", "LH")
    string = string.replace(u"ஷொ", "LI")
    string = string.replace(u"ஜொ", "LJ")
    string = string.replace(u"ஹொ", "LK")
    string = string.replace(u"க்ஷொ", "LL")
    
    string = string.replace(u"ஸோ", "LM")
    string = string.replace(u"ஷோ", "LN")
    string = string.replace(u"ஜோ", "LO")
    string = string.replace(u"ஹோ", "LP")
    string = string.replace(u"க்ஷோ", "LQ")
    
    string = string.replace(u"ஸௌ", "LR")
    string = string.replace(u"ஷௌ", "LS")
    string = string.replace(u"ஜௌ", "LT")
    string = string.replace(u"ஹௌ", "LU")
    string = string.replace(u"க்ஷௌ", "LV")
    
    string = string.replace(u"ஸ்", "LW")
    string = string.replace(u"ஷ்", "LX")
    string = string.replace(u"ஜ்", "LY")
    string = string.replace(u"ஹ்", "LZ")
    string = string.replace(u"க்ஷ்", "MA")
    
    string = string.replace(u"ஸ", "JN")
    string = string.replace(u"ஷ", "JO")
    string = string.replace(u"ஜ", "JP")
    string = string.replace(u"ஹ", "JQ")
    string = string.replace(u"க்ஷ", "JR")
    string = string.replace(u"ஶ்ரீ", "JS")
    
    return string

def enc(text):
    key = input('Enter your AES key: \n')
    #start = time.time()
    key_hash = md5(key.encode('ascii')).digest()
    mode = AES.MODE_EAX
    cipher = AES.new(key_hash, mode, nonce=b'0') ##AES ALGORITHM
    ciphertext = cipher.encrypt(text)
    return ciphertext


    
##ENCRYPTION
def send_email(receiver, subject, body):
    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login('tamilcipher@gmail.com', 'Abcdefgh1.')
    email = EmailMessage()
    email['From'] = 'tamilcipher@gmail.com'
    email['To'] = receiver
    email['Subject'] = subject
    body = body

    ##TEXT ATTACHMENT
    start = time.time()
    
    trans = tamiltrans(body)
    print('Translated Text: \n',trans.text)
    map = tamilmap(trans.text)
    print('Mapped Text: \n',map)
    text = bytes(map, 'utf-8')
    ciphertext = enc(text)
    print('Encrypted Text: \n',ciphertext)
    print('Encrypted Text as byte: \n',hexlify(ciphertext))
    print('Encrypted Text as string: \n',str(hexlify(ciphertext), "utf-8"))
    encbody = str(hexlify(ciphertext), "utf-8")
    
    print("--- %s seconds ---" % ((time.time() - start)*1000))
    print("CPU % used:", psutil.cpu_percent())
    #print(psutil.virtual_memory())  # physical memory usage
    print('memory % used:', psutil.virtual_memory()[2])
    print('disk % used:', psutil.disk_usage('/'))
    #print('disk % used:', psutil.disk_usage()[3])
        
    email.set_content(encbody)
    
    server.send_message(email)
    print('Mail sent sucessfully!!')


receiver = input('Enter the Receiver Mail : \n')
subject = input('Enter the Subject of the Mail : \n')
##receiver = 'prave.anand124@gmail.com'
##subject = 'Encrypt mail with attachment'
body = input('Enter the Body of the Mail : \n')

send_email(receiver, subject, body)
